-- Generated by scripts/backfill-places.mjs --emit-sql — do not hand-edit.
-- Backfills `places` / `post_places` (0015_places.sql) for posts that predate them,
-- including the seed posts from 0008.
--
-- Every coordinate here came from the bundled country-state-city dataset that the
-- create-post city picker itself is built from — zero Mapbox geocoding requests were
-- made to produce this file, and none are made to apply it.
--
-- Emitted as a migration rather than run as a one-off script so the rows are
-- reproducible across environments and need no service role key to apply.

insert into places (name, country_code, country_name, lat, lng) values
  ('El Calafate', 'AR', 'Argentina', -50.34075, -72.27682),
  ('Ushuaia', 'AR', 'Argentina', -54.81084, -68.31591),
  ('Lisbon', 'PT', 'Portugal', 38.71666667, -9.16666667),
  ('Porto', 'PT', 'Portugal', 41.14961, -8.61099),
  ('Kyoto', 'JP', 'Japan', 35.02107, 135.75385),
  ('Kanazawa', 'JP', 'Japan', 36.6, 136.61667),
  ('Reykjavík', 'IS', 'Iceland', 64.13548, -21.89541),
  ('Grindavík', 'IS', 'Iceland', 63.83849, -22.43931),
  ('Bergen', 'NO', 'Norway', 60.392, 5.328),
  ('Svolvær', 'NO', 'Norway', 68.23417, 14.56834),
  ('Queenstown', 'NZ', 'New Zealand', -45.03023, 168.66271),
  ('Wellington', 'NZ', 'New Zealand', -41.28664, 174.77557),
  ('Tilarán', 'CR', 'Costa Rica', 10.45878, -84.97513),
  ('Liberia', 'CR', 'Costa Rica', 10.63504, -85.43772),
  ('Abbadia San Salvatore', 'IT', 'Italy', 42.8812, 11.6722),
  ('Hanoi', 'VN', 'Vietnam', 21.0245, 105.84117),
  ('Hạ Long', 'VN', 'Vietnam', 20.95045, 107.07336),
  ('Hội An', 'VN', 'Vietnam', 15.87944, 108.335),
  ('Firá', 'GR', 'Greece', 36.42107, 25.43087),
  ('Athens', 'GR', 'Greece', 37.98376, 23.72784),
  ('Kathmandu', 'NP', 'Nepal', 27.70169, 85.3206),
  ('Namche Bazar', 'NP', 'Nepal', 27.80528, 86.71058),
  ('Grad Dubrovnik', 'HR', 'Croatia', 42.64861, 18.09397),
  ('Split', 'HR', 'Croatia', 43.50891, 16.43915),
  ('Seoul', 'KR', 'South Korea', 37.566, 126.9784),
  ('Busan', 'KR', 'South Korea', 35.10168, 129.03004),
  ('Dublin', 'IE', 'Ireland', 53.33306, -6.24889),
  ('Ennis', 'IE', 'Ireland', 52.84361, -8.98639),
  ('Highland', 'GB', 'United Kingdom', 57.5, -5),
  ('Portree', 'GB', 'United Kingdom', 57.41288, -6.19418),
  ('Cusco', 'PE', 'Peru', -13.52264, -71.96734),
  ('Ollantaytambo', 'PE', 'Peru', -13.25722, -72.26306),
  ('Puerto Princesa', 'PH', 'Philippines', 9.73917, 118.73528),
  ('Dapa', 'PH', 'Philippines', 9.75944, 126.05306),
  ('Medellín', 'CO', 'Colombia', 6.25184, -75.56359),
  ('Cartagena de Indias', 'CO', 'Colombia', 10.39972, -75.51444),
  ('Paris', 'FR', 'France', 48.8534, 2.3486),
  ('Chamonix-Mont-Blanc', 'FR', 'France', 45.92375, 6.86933),
  ('Zermatt', 'CH', 'Switzerland', 46.01998, 7.74863),
  ('Interlaken', 'CH', 'Switzerland', 46.68387, 7.86638),
  ('Jaipur', 'IN', 'India', 27, 76),
  ('Udaipur', 'IN', 'India', 24.33, 73.77),
  ('Jodhpur', 'IN', 'India', 21.90174, 70.0327),
  ('Bangkok', 'TH', 'Thailand', 13.75398, 100.50144),
  ('Chiang Mai', 'TH', 'Thailand', 18.79038, 98.98468),
  ('Ko Lanta', 'TH', 'Thailand', 7.53362, 99.08647),
  ('Sydney', 'AU', 'Australia', -33.86785, 151.20732),
  ('Byron Bay', 'AU', 'Australia', -28.64989, 153.61246),
  ('Cairns', 'AU', 'Australia', -16.90268, 145.75287),
  ('Marrakech', 'MA', 'Morocco', 31.63623, -8.01041),
  ('Chefchaouene', 'MA', 'Morocco', 35.16878, -5.2636),
  ('Errachidia', 'MA', 'Morocco', 31.75, -4.5),
  ('Oaxaca', 'MX', 'Mexico', 17.06542, -96.72365),
  ('Ciudad de México', 'MX', 'Mexico', 19.42847, -99.12766),
  ('Tulum', 'MX', 'Mexico', 20.22618, -87.51702),
  ('Banff', 'CA', 'Canada', 51.17622, -115.56982),
  ('Jasper Park Lodge', 'CA', 'Canada', 52.88633, -118.05625),
  ('Vancouver', 'CA', 'Canada', 49.24966, -123.11934),
  ('Rio de Janeiro', 'BR', 'Brazil', -22.92008, -43.33069),
  ('Ilha Grande', 'BR', 'Brazil', -2.84022, -41.82881),
  ('Rome', 'IT', 'Italy', 41.89193, 12.51133),
  ('Florence', 'IT', 'Italy', 43.77925, 11.24626),
  ('Venice', 'IT', 'Italy', 45.43713, 12.33265),
  ('Ljubljana', 'SI', 'Slovenia', 46.05108, 14.50513),
  ('Bled', 'SI', 'Slovenia', 46.36917, 14.11361),
  ('Ubud', 'ID', 'Indonesia', -8.5098, 115.2654),
  ('Kuta', 'ID', 'Indonesia', -8.72332, 115.17234),
  ('Klungkung', 'ID', 'Indonesia', -8.53333, 115.4),
  ('Berlin', 'DE', 'Germany', 52.52437, 13.41053),
  ('Munich', 'DE', 'Germany', 48.13743, 11.57549),
  ('Cape Town', 'ZA', 'South Africa', -33.92584, 18.42322),
  ('Stellenbosch', 'ZA', 'South Africa', -33.93462, 18.86676),
  ('Hermanus', 'ZA', 'South Africa', -34.4187, 19.23446),
  ('Fatih', 'TR', 'Turkey', 41.01746, 28.94053),
  ('Göreme', 'TR', 'Turkey', 38.6437, 34.83529),
  ('Antalya', 'TR', 'Turkey', 36.90812, 30.69556),
  ('Santiago', 'CL', 'Chile', -33.45694, -70.64827),
  ('Torres del Paine', 'CL', 'Chile', -51.26666667, -72.35),
  ('Barcelona', 'ES', 'Spain', 41.38879, 2.15899),
  ('Sevilla', 'ES', 'Spain', 37.38283, -5.97317),
  ('Tangier', 'MA', 'Morocco', 35.76727, -5.79975),
  ('Abbeville', 'FR', 'France', 50.10521, 1.83547),
  ('Luant', 'FR', 'France', 46.733, 1.55793)
on conflict (lower(btrim(name)), country_code) do nothing;

-- Links are derived by joining posts.destinations against the rows above rather than
-- being written out as id pairs, so this is environment-independent and safe to re-run:
-- it links whatever posts exist wherever it's applied.
insert into post_places (post_id, place_id)
select p.id, pl.id
from posts p
cross join lateral jsonb_array_elements(p.destinations) as d
cross join lateral jsonb_array_elements_text(coalesce(d->'cities', '[]'::jsonb)) as city
join places pl
  on pl.country_code = upper(btrim(d->>'countryCode'))
 and lower(btrim(pl.name)) = lower(btrim(city))
where d->>'mode' = 'focused'
on conflict do nothing;
